### ISSUE TITLE
Reasoning speed issue

### ISSUE THREAD

**Issue by liruiluo** [thuml/iVideoGPT#2]
It's a really good idea to use pre-trained interactive world models to speed up reinforcement learning training!
I am more concerned about the inference time, because it takes 2 seconds to infer 16 frames on an RTX 3090 GPU, and I am a little worried about how such speed can be applied to reinforcement learning training.

**Comment by Manchery** [comment]
Hi,

Thank you again for your interest!

It's a common issue for model-based RL to take more time compared to model-free methods. You mentioned that iVideoGPT takes 2 seconds to infer 16 frames on an RTX 3090 GPU. This is the speed of our raw inference example, which can be significantly accelerated through batching and mixed precision (we used bf16).

I took a quick look at my experiment logs, and for our implementation, it takes 1h 44m for model-free DrQ-v2 training with 150k Meta-world environment steps, and 6h 26m for MBPO with iVideoGPT. The increased overhead is due to world model fine-tuning and rollouts. All implementation details can be found in Appendix A.5 of our paper.

In future revisions of our paper, we will include detailed runtime statistics and analysis. Please let us know if you have any other questions!
