### ISSUE TITLE
a question about max_attn_resolution and crossattn layer numbers

### ISSUE THREAD

**Issue by yangyichu** [thuml/iVideoGPT#3]
I see in the provided example checkpoint, max_attn_resolution is set to be 16. So during encoding, the image will go through downblocks of 64x64, 32x32, 16x16, 16x16, cross_attn is added **twice** after 16x16 downblocks. Yet during decoding the image will go through 16x16, 32x32, 64x64, 64x64, and cross_attn is added **only once**, is this an expected behavior(resulting in asymmetric encoder and decoder structure)?

**Comment by Manchery** [comment]
Hi, thank you for your interest in our work!
﻿
You are correct. There are indeed two cross-attention blocks for the encoders but only one for the decoders. This wasn't an intentional design choice. Initially, the cross-attention mechanism was supposed to be applied to multi-scale features. However, I set the max_attn_resolution to 16 mainly to save memory usage. Despite this, the current architecture performs well in practice. I will conduct experiments with more cross-attention blocks (e.g., setting max_attn_resolution to 32) to see if this can further improve performance. Thank you for pointing this out to my attention!

**Comment by Zhao-ZD** [comment]
great work,may i ask if 512x512 version will be released

**Comment by Manchery** [comment]
> great work,may i ask if 512x512 version will be released

Thanks for your interest in our work! @Zhao-ZD  Due to limited computational resources, we do not have a such high-resolution version on 512x512.

**Comment by Manchery** [comment]
> I see in the provided example checkpoint, max_attn_resolution is set to be 16. So during encoding, the image will go through downblocks of 64x64, 32x32, 16x16, 16x16, cross_attn is added **twice** after 16x16 downblocks. Yet during decoding the image will go through 16x16, 32x32, 64x64, 64x64, and cross_attn is added **only once**, is this an expected behavior(resulting in asymmetric encoder and decoder structure)?

We have released pretrained models for high-resolution (256x256) with more than one attention block in the decoder (exactly 3 in encoder and 2 in decoder). The asymmetric encoder-decoder design is due to historical reasons and following the original Taming-VQGAN. A recent paper (https://arxiv.org/abs/2409.16211) reports that a symmetric design can improve the VQGAN. I believe it also holds for the tokenizer of iVideoGPT, but this needs more computation resources and experiments to justify.

If there are any questions, I remain open to discussing them.
